disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - unused_closure_parameter
  - implicit_getter
  - force_try

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods